# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('game_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
